### PR TITLE
Add vendors

### PR DESCRIPTION
**Pull request by wipfli**

### CODE REVIEW

**Comment by wipfli** [comment]
Because it seemed circular, but I think we can have links to other awesome lists actually.

**Comment by wipfli** [comment]
How much personal opinion should we put into this actually? Other awesome lists just give neutral descriptions. Maybe the fact that something is on this list already means that it is awesome and we don't need to make a distinction between better and worse?

**Comment by carmelom** [comment]
It's also awesome to get feedback from past experience. We could have just neutral description lists and then "blacklists" or "review" sections

**Comment by wipfli** [comment]
I propose to keep the readme neutral but only good stuff goes in there. 

In the issues, we (and others) can share experiences and be as opinionated as we want.

**Review by carmelom — APPROVED** [review]

**Pull request merged**
