### PR TITLE
add Open Quantum Hardware Projects

### PR DESCRIPTION
**Pull request by sergachev**

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks for the new link. Please join the org, then you can merge this yourself.

**Review by wipfli — APPROVED** [review]

**Comment by sergachev** [comment]
already joined but have no write access

**Comment by wipfli** [comment]
I changed the default member privilege from read to write. Can you merge now @sergachev ?

**Comment by sergachev** [comment]
it seems so

**Pull request merged**
